import React, { useState, useEffect } from 'react';
import { supabase } from '../supabaseClient';
import { DollarSign, FileText, CreditCard, TrendingUp, Download, CheckCircle, AlertCircle, RefreshCw, ChevronRight, Settings, Save, CheckSquare } from 'lucide-react';
import { useInvoices } from '../context/InvoiceContext';
import InvoiceDocumentModal from '../components/InvoiceDocumentModal';
import './Proposals.css';

export default function Finance() {
  const [activeTab, setActiveTab] = useState('overview');
  const [margins, setMargins] = useState({ good_margin: 0.35, better_margin: 0.40, best_margin: 0.45, service_reserve: 0.05, sales_tax: 0.07 });
  const { invoices, updateInvoice } = useInvoices();
  
  // Modals
  const [loggingCheckFor, setLoggingCheckFor] = useState(null);
  const [viewingInvoice, setViewingInvoice] = useState(null);

  useEffect(() => {
    fetchMargins();
  }, []);

  const fetchMargins = async () => {
    const { data } = await supabase.from('margin_settings').select('*').eq('id', 1).single();
    if (data) setMargins(data);
  };

  const saveMargins = async () => {
    await supabase.from('margin_settings').update(margins).eq('id', 1);
    alert('Global margins updated! All future estimates will use these rates.');
  };

  const handleLogCheck = async (invoice) => {
      // In a real app we'd open a modal. For now, let's just mark it!
      const checkNumber = prompt(`Log Check Payment for ${invoice.customer}\nEnter Check/Routing Number:`);
      if (checkNumber) {
          await updateInvoice(invoice.id, {
              status: 'Paid',
              payment_method: `Check #${checkNumber}`,
              paid_at: new Date().toISOString()
          });
      }
  };

  const pendingInvoices = invoices.filter(i => i.status !== 'Paid');
  const totalGross = invoices.reduce((sum, i) => sum + Number(i.amount || 0), 0);
  const totalOutstanding = pendingInvoices.reduce((sum, i) => sum + Number(i.amount || 0), 0);
  const overdueCount = pendingInvoices.filter(i => i.status === 'Overdue').length;

  const renderTabContent = () => {
    if (activeTab === 'overview') {
      return (
        <div className="fade-in">
          <div className="grid grid-cols-4 gap-6 mb-8">
            <div className="glass-panel p-6 flex flex-col gap-2">
              <span className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Gross Billed (YTD)</span>
              <span className="text-3xl font-bold text-slate-800">${totalGross.toLocaleString()}</span>
              <span className="text-sm text-success flex items-center"><TrendingUp size={14} className="mr-1" /> Ledger Live</span>
            </div>
            <div className="glass-panel p-6 flex flex-col gap-2 relative overflow-hidden">
               {totalOutstanding > 0 && <div className="absolute top-0 right-0 w-2 h-full bg-primary-500"></div>}
               <span className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Outstanding Accounts</span>
               <span className="text-3xl font-bold text-slate-800">${totalOutstanding.toLocaleString()}</span>
               <span className={`text-sm flex items-center ${overdueCount > 0 ? 'text-danger' : 'text-slate-500'}`}><AlertCircle size={14} className="mr-1" /> {overdueCount} Overdue</span>
            </div>
            <div className="glass-panel p-6 flex flex-col gap-2">
               <span className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Automated Workflows</span>
               <span className="text-3xl font-bold text-slate-800">{invoices.length}</span>
               <span className="text-sm text-slate-500 flex items-center">Invoices Autogenerated</span>
            </div>
            <div className="glass-panel p-6 flex flex-col justify-between">
               <div>
                 <span className="text-sm font-semibold text-slate-500 uppercase tracking-wider block mb-2">Integration Status</span>
                 <div className="flex items-center gap-2 mb-1">
                   <div className="w-2 h-2 rounded-full bg-success"></div>
                   <span className="text-sm font-semibold">Live Pilar Automations</span>
                 </div>
                 <div className="flex items-center gap-2">
                   <div className="w-2 h-2 rounded-full bg-success"></div>
                   <span className="text-sm font-semibold">Dispatch Polling Active</span>
                 </div>
               </div>
               <button className="text-sm text-primary-600 font-semibold flex items-center gap-1 mt-2">
                 <RefreshCw size={14} /> Force Sync Now
               </button>
            </div>
          </div>

          <div className="bg-white rounded-md shadow-sm border border-slate-200 overflow-hidden">
            <div className="flex justify-between items-center p-4 border-b border-slate-200 bg-slate-50">
              <h3 className="font-bold text-slate-800">Master Invoice Directory</h3>
              <button className="text-sm font-semibold text-primary-600">Download CSV</button>
            </div>
            {invoices.length === 0 ? (
                <div className="p-8 text-center text-slate-500">
                   No invoices have been generated yet. Complete a Work Order in the Dispatch Hub to auto-spawn an invoice.
                </div>
            ) : (
                <table className="w-full text-left border-collapse" style={{ width: '100%' }}>
                <thead>
                    <tr className="bg-white border-b border-slate-200 text-sm text-slate-500 uppercase tracking-wider">
                    <th className="p-4 font-semibold text-[10px]">Invoice ID</th>
                    <th className="p-4 font-semibold text-[10px]">Customer / Account</th>
                    <th className="p-4 font-semibold text-[10px]">Issued Date</th>
                    <th className="p-4 font-semibold text-[10px]">Total Amount</th>
                    <th className="p-4 font-semibold text-[10px]">Payment Method</th>
                    <th className="p-4 font-semibold text-[10px]">Status</th>
                    <th className="p-4 font-semibold text-[10px]"></th>
                    </tr>
                </thead>
                <tbody>
                    {invoices.map(inv => (
                    <tr key={inv.id} className="border-b border-slate-100 hover:bg-slate-50 transition-colors">
                        <td className="p-4 font-bold text-slate-800 text-xs">{inv.id}</td>
                        <td className="p-4 font-bold text-primary-800">{inv.customer}</td>
                        <td className="p-4 text-slate-500 text-sm font-medium">{new Date(inv.issued_at).toLocaleDateString()}</td>
                        <td className="p-4 font-black text-slate-800">${Number(inv.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                        <td className="p-4 text-slate-500 text-sm font-medium">{inv.payment_method || '-'}</td>
                        <td className="p-4">
                        {inv.status === 'Paid' && <span className="bg-emerald-100 text-emerald-800 border border-emerald-200 px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider">{inv.status}</span>}
                        {inv.status === 'Pending' && <span className="bg-slate-100 text-slate-600 border border-slate-200 px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider">{inv.status}</span>}
                        {inv.status === 'Overdue' && <span className="bg-rose-100 text-rose-800 border border-rose-200 px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider">{inv.status}</span>}
                        </td>
                        <td className="p-4 text-right flex gap-2 justify-end">
                            {inv.status !== 'Paid' && (
                                <button className="text-[10px] font-bold text-primary-600 bg-primary-50 hover:bg-primary-100 px-3 py-1.5 rounded uppercase tracking-wider border border-primary-200 flex items-center gap-1" onClick={() => handleLogCheck(inv)}>
                                    <CheckSquare size={12} /> Log Pay
                                </button>
                            )}
                            <button className="text-slate-400 hover:text-slate-800 bg-slate-100 hover:bg-slate-200 p-1.5 rounded transition-fast" title="Download PDF" onClick={() => setViewingInvoice(inv)}><Download size={14} /></button>
                        </td>
                    </tr>
                    ))}
                </tbody>
                </table>
            )}
          </div>
        </div>
      );
    }
    
    if (activeTab === 'pricing') {
      return (
        <div className="fade-in max-w-xl">
           <div className="glass-panel p-8 relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-primary-100 rounded-bl-full -z-10 opacity-50 group-hover:scale-110 transition-transform"></div>
              <h3 className="font-bold text-slate-800 flex items-center gap-2 mb-2 text-xl"><Settings className="text-primary-500"/> Global Pricing Engine</h3>
              <p className="text-slate-500 text-sm mb-8">Update the baseline logic math used across all sales proposals and catalog generation. These variables natively control retail prices.</p>
              
              {/* Settings layout omitted for brevity, exact same as before */}
              <div className="flex justify-between items-center mb-4 bg-white p-4 rounded-lg border border-slate-100 shadow-sm">
                 <span className="font-semibold text-slate-700">Good Tier Target Margin</span>
                 <div className="flex items-center gap-2">
                   <input type="number" step="0.1" className="border-b-2 border-primary-500 focus:outline-none p-1 w-20 text-right font-bold text-primary-700 bg-transparent text-lg" value={Number(((margins.good_margin || 0.35) * 100).toFixed(2))} onChange={e => setMargins({...margins, good_margin: parseFloat(e.target.value) / 100})} />
                   <span className="font-bold text-slate-400">%</span>
                 </div>
              </div>

              <div className="flex justify-between items-center mb-4 bg-white p-4 rounded-lg border border-slate-100 shadow-sm">
                 <span className="font-semibold text-slate-700">Better Tier Target Margin</span>
                 <div className="flex items-center gap-2">
                   <input type="number" step="0.1" className="border-b-2 border-primary-500 focus:outline-none p-1 w-20 text-right font-bold text-primary-700 bg-transparent text-lg" value={Number(((margins.better_margin || 0.40) * 100).toFixed(2))} onChange={e => setMargins({...margins, better_margin: parseFloat(e.target.value) / 100})} />
                   <span className="font-bold text-slate-400">%</span>
                 </div>
              </div>

              <div className="flex justify-between items-center mb-4 bg-white p-4 rounded-lg border border-slate-100 shadow-sm">
                 <span className="font-semibold text-slate-700">Best Tier Target Margin</span>
                 <div className="flex items-center gap-2">
                   <input type="number" step="0.1" className="border-b-2 border-primary-500 focus:outline-none p-1 w-20 text-right font-bold text-primary-700 bg-transparent text-lg" value={Number(((margins.best_margin || 0.45) * 100).toFixed(2))} onChange={e => setMargins({...margins, best_margin: parseFloat(e.target.value) / 100})} />
                   <span className="font-bold text-slate-400">%</span>
                 </div>
              </div>
              
              <div className="flex justify-between items-center mb-4 bg-white p-4 rounded-lg border border-slate-100 shadow-sm">
                 <span className="font-semibold text-slate-700">Service Reserve Injection</span>
                 <div className="flex items-center gap-2">
                   <input type="number" step="0.1" className="border-b-2 border-primary-500 focus:outline-none p-1 w-20 text-right font-bold text-primary-700 bg-transparent text-lg" value={Number(((margins.service_reserve || 0.05) * 100).toFixed(2))} onChange={e => setMargins({...margins, service_reserve: parseFloat(e.target.value) / 100})} />
                   <span className="font-bold text-slate-400">%</span>
                 </div>
              </div>

              <div className="flex justify-between items-center mb-8 bg-white p-4 rounded-lg border border-slate-100 shadow-sm">
                 <span className="font-semibold text-slate-700">State Sales Tax</span>
                 <div className="flex items-center gap-2">
                   <input type="number" step="0.1" className="border-b-2 border-primary-500 focus:outline-none p-1 w-20 text-right font-bold text-primary-700 bg-transparent text-lg" value={Number(((margins.sales_tax || 0.07) * 100).toFixed(2))} onChange={e => setMargins({...margins, sales_tax: parseFloat(e.target.value) / 100})} />
                   <span className="font-bold text-slate-400">%</span>
                 </div>
              </div>
              
              <button 
                className="text-white font-semibold text-sm flex items-center gap-2 w-full justify-center bg-slate-800 py-4 rounded-lg hover:bg-slate-900 shadow-md transition-all active:scale-95" 
                onClick={saveMargins}
              >
                <Save size={18}/> Apply Logic Universally
              </button>
           </div>
        </div>
      );
    }
    
    if (activeTab === 'checks') {
      return (
        <div className="fade-in max-w-2xl">
          <div className="glass-panel p-8">
            <div className="flex items-center gap-4 mb-6 pb-6 border-b border-slate-100">
                <div className="p-4 bg-primary-50 rounded-full text-primary-600"><FileText size={32}/></div>
                <div>
                   <h2 className="text-xl font-bold text-slate-800">Check & Cash Ledgers</h2>
                   <p className="text-slate-500 text-sm">Select an outstanding invoice below to mark it as collected.</p>
                </div>
            </div>

            <div className="flex flex-col gap-3">
                {pendingInvoices.length === 0 && <p className="text-slate-500 italic">No pending invoices require collection!</p>}
                {pendingInvoices.map(inv => (
                    <div key={inv.id} className="flex items-center justify-between p-4 border border-slate-200 rounded-lg bg-white shadow-sm">
                        <div>
                            <p className="font-bold text-slate-800">{inv.customer}</p>
                            <p className="text-xs text-slate-500 uppercase font-black tracking-wider">{inv.id} • ${Number(inv.amount).toLocaleString()}</p>
                        </div>
                        <button 
                            className="bg-primary-600 hover:bg-primary-700 text-white font-bold text-xs uppercase tracking-wider py-2 px-4 rounded shadow-sm"
                            onClick={() => handleLogCheck(inv)}
                        >
                            Record Payment
                        </button>
                    </div>
                ))}
            </div>
          </div>
        </div>
      );
    }
  };

  return (
    <div className="page-container fade-in">
      <header className="page-header">
        <div>
          <h1 className="page-title">Finance & Accounting</h1>
          <p className="page-subtitle">Track YTD revenue, auto-issued invoices, and reconcile uncollected balances</p>
        </div>
      </header>

      {/* Custom Tab Navigation */}
      <div className="flex gap-1 bg-slate-100/50 p-1.5 rounded-xl w-max mb-8 border border-slate-200/50 shadow-sm backdrop-blur-sm">
        <button 
          onClick={() => setActiveTab('overview')}
          className={`px-5 py-2.5 font-bold text-xs uppercase tracking-wider rounded-lg transition-all duration-300 ${activeTab === 'overview' ? 'bg-white shadow-md text-primary-700 border-b-2 border-primary-500' : 'text-slate-500 hover:text-slate-700 hover:bg-slate-100/50'}`}
        >
          Ledger Overview
        </button>
        <button 
          onClick={() => setActiveTab('checks')}
          className={`px-5 py-2.5 font-bold text-xs uppercase tracking-wider rounded-lg transition-all duration-300 flex items-center gap-2 ${activeTab === 'checks' ? 'bg-white shadow-md text-primary-700 border-b-2 border-primary-500' : 'text-slate-500 hover:text-slate-700 hover:bg-slate-100/50'}`}
        >
          Check Collections {pendingInvoices.length > 0 && <span className="bg-danger text-white px-1.5 py-0.5 rounded text-[9px]">{pendingInvoices.length}</span>}
        </button>
        <button 
          onClick={() => setActiveTab('pricing')}
          className={`px-5 py-2.5 font-bold text-xs uppercase tracking-wider rounded-lg transition-all duration-300 ${activeTab === 'pricing' ? 'bg-white shadow-md text-primary-700 border-b-2 border-primary-500' : 'text-slate-500 hover:text-slate-700 hover:bg-slate-100/50'}`}
        >
          Pricing Logic Data
        </button>
      </div>

      <div className="mt-4">
        {renderTabContent()}
      </div>

      <InvoiceDocumentModal 
         isOpen={!!viewingInvoice} 
         onClose={() => setViewingInvoice(null)} 
         invoiceData={viewingInvoice} 
      />
    </div>
  );
}
