-- scripts/phase_13_invoice_templates.sql
-- Run this in the Supabase SQL Editor to expand the template configurations for dynamic Invoices

ALTER TABLE public.contract_templates
ADD COLUMN IF NOT EXISTS invoice_customer_message TEXT DEFAULT 'Thank you for your business. Please contact us if you have any questions regarding this invoice or your service.',
ADD COLUMN IF NOT EXISTS invoice_footer_text TEXT DEFAULT 'Invoice generated by Pilar Sales Platform',
ADD COLUMN IF NOT EXISTS invoice_payment_terms TEXT DEFAULT 'Due upon receipt';

-- To ensure the API exposes these new columns immediately without issues, reload the schema cache.
NOTIFY pgrst, 'reload schema';
